# Generated by Django 6.0.6 on 2026-06-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocgs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='satus',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Drafts')], default='Draft', max_length=20),
        ),
    ]
