# Generated by Django 6.0.6 on 2026-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocgs', '0005_alter_blog_satus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='satus',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
